# Enable/Disable tnt igniter features
isActive: true

#####################################
#
# Manage where you can use the tnt igniter feature.
#

# Use spigot worlds names
allowed_world:
- "world"
- "anotherWorld"

# Need WorldGuard plugin
disabled_area:
- "spawn"

disabled_player:
- "a uuid or name"

# Permission for using the auto ignite.
# EMPTY FOR DISABLE IT
# 
ignite_perm: ""

#####################################
#
# Manage launch effect of TNT
#
launch:
  # Enable/Disable it
  enable: true

  # When the launcher have to be used
  # Click available:
  # 'right' : Only the right click
  # 'left' : Only the left click
  # 'both' : All click
  click: "right"
  # With available:
  # 'air' : Only when click on air
  # 'block' : Only when click on block
  # 'both' : When click on something
  with: "both"

  # Vector added to the primed tnt.
  # The default one is just here to make the tnt go up and not fall directly
  vector:
    x: 0
    y: 0.5
    z: 0

#####################################
#
# All messages used by the plugin
#
reloaded: "&aThe plugin is well reloaded"
active_enable: "&aNow, TnT will be ignite when you place it."
active_disable: "&aTnT are no longer ignite when you place it."
already_enable: "TnT are already igniting ..."
already_disable: "TnT igniting is already disabled."
world_allowed: "World allowed: %world%"
unknow_world: "%arg% isn't a valid world."
world_state: "%world% %state%"
state_added: "added"
state_removed: "removed"
not_permission: "&cYou don't have permission to do that."